import {analyzeMessage} from "../analysis-engine.js";
import {normalizeDomain,senderDomain,verifyDomain} from "../domain-verifier.js";
const $=id=>document.getElementById(id),views=["composer","loading","error","result"];let installPrompt;
const show=id=>views.forEach(v=>$(v).classList.toggle("hidden",v!==id));
function extract(raw){const value=String(raw||"").trim(),lines=value.split(/\r?\n/);const header=names=>{const rx=new RegExp("^\\s*(?:"+names.join("|")+")\\s*:\s*(.+)$","i");return lines.map(line=>{const m=line.match(rx);return m&&m[1]?m[1].trim():""}).find(Boolean)||""};const found=[...value.matchAll(/https?:\/\/[^\s<>"']+|www\.[^\s<>"']+/gi)].map(m=>m[0].replace(/[),.;!?]+$/,"") );const urls=[...new Set(found)];return{sender:header(["de","from","remitente"]),subject:header(["asunto","subject"]),body:value,text:value,links:urls.map(url=>({href:url,text:url})),provider:"Móvil"}}
function firstDomain(data){const from=senderDomain(data.sender);if(from)return from;for(const link of data.links){try{return normalizeDomain(new URL(/^https?:/i.test(link.href)?link.href:"https://"+link.href).hostname)}catch{}}return""}
function withDomain(base,report){if(!report||!report.riskPoints)return base;const reasons=base.reasons.filter(r=>r.id!=="domain-verification");reasons.push({id:"domain-verification",points:report.riskPoints,title:"Verificación pública del dominio",detail:report.warnings.join(" ")||"El dominio requiere cautela.",evidence:report.registered});const score=Math.min(100,base.score+report.riskPoints),level=score>=65?"high":score>=35?"medium":"low";const recommendation=level==="high"?"No pulses enlaces ni respondas. Verifica la solicitud mediante un canal oficial independiente.":level==="medium"?"Comprueba el remitente y el destino real de los enlaces antes de actuar.":base.recommendation;return{...base,score,level,recommendation,reasons:reasons.sort((a,b)=>b.points-a.points)}}
function renderReasons(reasons){const box=$("reasons");box.replaceChildren();if(!reasons.length){const e=document.createElement("div");e.className="empty";e.textContent="No se detectaron señales locales destacables.";box.append(e);return}reasons.forEach(r=>{const a=document.createElement("article"),h=document.createElement("h3"),p=document.createElement("p");a.className="reason";h.textContent=r.title+" (+"+r.points+")";p.textContent=r.detail;a.append(h,p);if(r.evidence){const c=document.createElement("code");c.textContent=r.evidence;a.append(c)}box.append(a)})}
function renderDomain(report){const box=$("domain-report");box.replaceChildren();if(!report){box.classList.add("hidden");return}box.classList.remove("hidden");const h=document.createElement("h2"),dl=document.createElement("dl");h.textContent="Dominio comprobado: "+report.registered;dl.className="domain-grid";[["DNS",report.exists?"Encontrado":"No encontrado"],["Correo MX",report.mx?"Sí":"No"],["SPF",report.spf?"Publicado":"No encontrado"],["DMARC",report.dmarc?"Publicado":"No encontrado"],["Antigüedad",report.ageDays===null?"No disponible":report.ageDays+" días"],["Impacto",report.riskPoints?"+"+report.riskPoints+" puntos":"Sin aumento"]].forEach(row=>{const dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=row[0];dd.textContent=row[1];dl.append(dt,dd)});box.append(h,dl);if(report.warnings.length){const ul=document.createElement("ul");ul.className="warnings";report.warnings.forEach(w=>{const li=document.createElement("li");li.textContent=w;ul.append(li)});box.append(ul)}}
function render(data,result,report){$("score-card").className=result.level;$("risk-label").textContent={low:"RIESGO BAJO",medium:"RIESGO MEDIO",high:"RIESGO ALTO"}[result.level];$("score").textContent=result.score;$("recommendation").textContent=result.recommendation;$("sender").textContent=data.sender||"No indicado";$("subject").textContent=data.subject||"No indicado";$("link-count").textContent=result.summary.linksAnalyzed;renderReasons(result.reasons);renderDomain(report);show("result");scrollTo(0,0)}
async function analyze(){const raw=$("content").value.trim();if(!raw){$("error-text").textContent="Pega primero el mensaje o un enlace.";show("error");return}show("loading");try{const data=extract(raw),base=analyzeMessage(data),domain=firstDomain(data);let report=null;if(domain){$("loading-text").textContent="Verificando públicamente el dominio.";try{report=await verifyDomain(domain)}catch{}}render(data,withDomain(base,report),report)}catch(error){$("error-text").textContent=error.message||"Ha ocurrido un error inesperado.";show("error")}}
$("analyze").addEventListener("click",analyze);$("again").addEventListener("click",()=>{show("composer");$("content").focus();scrollTo(0,0)});$("error-back").addEventListener("click",()=>show("composer"));$("paste").addEventListener("click",async()=>{try{$("content").value=await navigator.clipboard.readText()}catch{$("error-text").textContent="Mantén pulsado el cuadro y elige Pegar.";show("error")}});
addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;$("install-bar").classList.remove("hidden")});$("install").addEventListener("click",async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$("install-bar").classList.add("hidden")}});$("dismiss").addEventListener("click",()=>$("install-bar").classList.add("hidden"));
if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js"));const q=new URLSearchParams(location.search),shared=[q.get("title"),q.get("text"),q.get("url")].filter(Boolean).join("\n");if(shared){$("content").value=shared;history.replaceState({},"",location.pathname);analyze()}
